services:
  sanaa-web-research:
    image: python:3.11-slim
    container_name: sanaa-web-research
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - REQUEST_TIMEOUT=10
      - MAX_CONTENT_LENGTH=50000
      - REQUESTS_PER_MINUTE=10
      - ALLOWED_DOMAINS=docs.npmjs.com,reactjs.org,laravel.com,flutter.dev,developer.mozilla.org,stackoverflow.com,github.com,pypi.org,pub.dev
    volumes:
      - ./packages:/app/packages:ro
      - ./web_cache:/app/web_cache
      - ~/.sanaa/web_cache:/app/web_cache
    networks:
      - sanaa-network
    command: >
      python3 -c "
      import asyncio
      from packages.agents.src.coding_swarm_agents.web_research_agent import WebResearchAgent

      async def main():
          agent = WebResearchAgent({'project': '.', 'goal': 'Web research service'})
          print('Web Research Agent started and ready for queries')
          # Keep service running
          while True:
              await asyncio.sleep(60)

      asyncio.run(main())
      "
    healthcheck:
      test: ["CMD", "python3", "-c", "import httpx; print('Web client available')"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN

  sanaa-web-proxy:
    image: nginx:alpine
    container_name: sanaa-web-proxy
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sanaa-network
    depends_on:
      - sanaa-web-research
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL

networks:
  sanaa-network:
    driver: bridge
    internal: true  # Isolated network for security