[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coding-swarm-agents"
version = "0.1.0"
description = "AI agent implementations"
requires-python = ">=3.11"
dependencies = [
  "coding-swarm-core>=0.1.0",
  "httpx>=0.27.0",
  "pydantic>=2.0.0",
  "fastapi>=0.104.0",
  "openai>=1.0.0",
  "anthropic>=0.8.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/coding_swarm_agents"]
