[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coding-swarm-core"
version = "0.1.0"
description = "Core utilities for Coding Swarm"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.0.0", "httpx>=0.27.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/coding_swarm_core"]
