[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coding-swarm-orchestrator"
version = "0.1.0"
description = "Task orchestration for Coding Swarm"
requires-python = ">=3.11"
dependencies = [
  "coding-swarm-core>=0.1.0",
  "coding-swarm-agents>=0.1.0",
  "pydantic>=2.0.0",
  "httpx>=0.27.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/coding_swarm_orchestrator"]
